version: '2'
services:
  boot211:
    container_name: boot211
    build: 
      context: .
      dockerfile: Dockerfile
    image: boot211:latest
    expose: 
      - 4100
    ports:
      - 4100:4100  
